### ISSUE TITLE
Edit Tool Shortcut Issues Hoot Release

### ISSUE THREAD

**Issue by kweint** [ngageoint/hootenanny-ui#1005]
![hootedittoolbehavior](https://user-images.githubusercontent.com/18521019/37060936-c981172e-215f-11e8-8bac-616f1247efcd.gif)

In the above GIF notice how I can activate an edit tool with shortcuts, but I have to mouse click in order to deactivate that edit tool.

**Comment by damianblanck** [comment]
@kweint can you clarify what the issue is. At this zoom scale I would think you shouldn't be able to invoke any of the buttons. Hoot while integrated to iD was meant for conflation. Maybe all the buttons should be disabled until after conflation, when you are trying to fix conflation issues? And at that point maybe adding something that wasn't in either dataset. Seems like the current gif is out beyond zoom level 15.

**Comment by sisskind** [comment]
The issue is the hotkeys engage but if you want to cancel or not draw the feature they do not disengage. This is the behavior in MapEdit.
