### ISSUE TITLE
see if any of our dependencies bloat our bundle.

### ISSUE THREAD

**Issue by maxgrossman** [ngageoint/hootenanny-ui#1432]
ref #1373 

We should probably see which of our dependencies bloat the bundle size and try to achieve what they achieve with vanilla javascript, or just remove them if not needed. always better to make our code small.

**Comment by maxgrossman** [comment]
to avoid ticket inception, here's the bundle @brianhatchl found!

https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by maxgrossman** [comment]
![image](https://user-images.githubusercontent.com/15100429/58014933-fe988600-7ac7-11e9-979a-6ac16c3a2b19.png)

[bundle_stats.json.zip](https://github.com/ngageoint/hootenanny-ui/files/3197395/bundle_stats.json.zip)

**Comment by maxgrossman** [comment]
The JSON file will provide more details.
I'm not sure an immediate solution for presets/imagery, however, the combined size of moment.js, lodash-es, and jquery is big enough such that we should probably try to just use vanilla javascript (much like the iD folks already have).

**Comment by maxgrossman** [comment]
also the size properties in the json file are in bytes...

**Comment by maxgrossman** [comment]
just note, when we bundle all of the javascript in production, the little modules block accounts for all of the external libs we use, which in the image below is something like 390kb....
![image](https://user-images.githubusercontent.com/15100429/58015951-81badb80-7aca-11e9-8864-aaf9811558b7.png)

**Comment by maxgrossman** [comment]
so really, the bloat seems to be the imagery and presets...

**Comment by brianhatchl** [comment]
ok, so still really don't need jquery, so I think removing is still a good idea.  I guess I'm a bit disappointed about the size of the `login.min.js`.  The point of breaking it up (index.html vs login.html) was to hopefully have a lighter-weight login page.  It's pretty much a copy now.  I guess that's because it needed the `verifyOauth()` method from the api class.  I'll create a ticket to move it out to the login class #1433.
