### ISSUE TITLE
Login.html should redirect to index.html if valid session exists

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#1445]
right now it forces the user to generate a new oauth token and spring session when it's not necessary.

We might even consider collapsing the login code into index.html the way it was in hoot1

**Comment by maxgrossman** [comment]
@jackgrossman18 and I spent some time trying to understand better when a user needs to login when they just recently logged in.

It appears that so long as you do not close your browser, opening a new tab or refreshing your page does not whack the `SESSION` header that spring uses to keep track of your authorized session. Closing and re-opening your browser does. 

Perhaps a bit naive to use this as a standard to go by, but it seems that login.gov has similar behavior, so perhaps there is not a need to for updating the login setup. @brianhatch's assumption that the session cookie that we get from spring is indeed available at the domain/resource level, so switching pages is fine.

Maybe the issue then is something we handle in services. Rather than create a new record each time a user needs to login, we update a row that tracks user + user-agent?
