### ISSUE TITLE
Advanced options show incorrect default values when Attribute Conflation is selected

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1583]
Attribute Conflation defaults `building.keep.more.complex.geometry.when.auto.merging=false` as defined in AttributeConflation.conf. Select "Attribute Conflation" as the conflation type from the UI, open the Advanced Options and you see "Keep more complex geometry when merging" set to true under "Building Options".

**Comment by maxgrossman** [comment]
Great find. We have code in the UI that keeps those sidebar options in sync with the conflation type you choose. But, it only updates the grouping in the sidebar that shares the name. 

So, in this case, because we put the above option in `buildings`, not `attribute`

We could add more code to fix this, or we could just move the option to the attribute section.

**Comment by maxgrossman** [comment]
we can probably just do this with code, just need to change a condition
