### ISSUE TITLE
Multi-select for folders in datasets panel would be nice

### ISSUE THREAD

**Issue by brianhatchl** [ngageoint/hootenanny-ui#1614]

**Comment by jackgrossman18** [comment]
This ticket allows for multi-select of folders in the dataset modal. 

This new feature required several updates to the datasets, modifyFolder and folderTree classes. 

**Dataset**

Adding multi-select folder feature to the folderContextMenu required updating this class so that it can pass all the selected folders to the modifyFolder class, previously, it would just pass the single folder to the modifyFolder class, now it passes the selected folders as an object array.

**modifyFolders**

Selecting multiple folders requires this class to filter through all of the current Hoot folders, then return only those folders that make sense as a destination, this is a list of the prevented destinations.

_Prevented Destinations_

1. Either of the selected folders.
2. Any of the children of the selected folders.
3. The parent of either of the selected folders 

_Acceptable Destinations_
1. Root
2. Sibling folder of the selected folders.
3. Any folder that is a sibling of the parent of the selected folder(s)

**folderTree**

The modify folder class required a few updates to handle the application of the new ctrl key event, previously only used to select multiple datasets, now listening for the selection of multiple folders.

The changes made also required updates to assure that they were congruous with both the new multi-select dataset action, and the additions recently made to the folderTree ( #1626 & #1627). 

When multiple folders are selected, the `folderContextMenu` only allows for thee options. This is because the list of options that are available when a single folder is selected contains a few that aren't relevant. 

_Available options_

1. Delete the selected folders
2. Move the selected folders
3. Export the selected folders

_Removed options_

1. The user shouldn't be able to rename the folders that they are moving, this is better suited when only a single folder is selected.
2. Adding either a single or multiple datasets makes more sense, and avoids problems, when a single folder is selected.
3. Adding a folder to two separate folders doesn't seem like the best idea.
