### ISSUE TITLE
Matcher ordering incorrect for diff conflate and causes output discrepancy

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#1764]
Patrick found this. Below is a command he sent from the UI to do a diff. That matchers/mergers passed are incomplete and out of order. Matcher ordering has always been important, but now it is even moreso that we have Generic Conflation (and soon, collection relation conflation). This command gives a different output than the same one executed with the matchers/mergers in the default ordering from `ConfigOptions.asciidoc`.

`hoot conflate --info -C DifferentialConflation.conf -D writer.include.conflate.score.tags=false -D hootapi.db.writer.overwrite.map=true -D writer.text.status=true -D job.id=779e9999-5ff2-4798-8bda-842314a9687a -D api.db.email=1000000992@hootenanny -D match.creators=;hoot::ScriptMatchCreator,Area.js;hoot::ScriptMatchCreator,Line.js;hoot::ScriptMatchCreator,Point.js;hoot::ScriptMatchCreator,PointPolygon.js;hoot::ScriptMatchCreator,Polygon.js;hoot::ScriptMatchCreator,Poi.js;hoot::PoiPolygonMatchCreator;hoot::HighwayMatchCreator -D merger.creators=;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::PoiPolygonMergerCreator;hoot::HighwayMergerCreator -D differential.snap.unconnected.roads=true hootapidb://${HOOTAPI_DB_USER}:${HOOTAPI_DB_PASSWORD}@${HOOTAPI_DB_HOST}:${HOOTAPI_DB_PORT}/${HOOTAPI_DB_NAME}/3891 hootapidb://${HOOTAPI_DB_USER}:${HOOTAPI_DB_PASSWORD}@${HOOTAPI_DB_HOST}:${HOOTAPI_DB_PORT}/${HOOTAPI_DB_NAME}/3892 hootapidb://${HOOTAPI_DB_USER}:${HOOTAPI_DB_PASSWORD}@${HOOTAPI_DB_HOST}:${HOOTAPI_DB_PORT}/${HOOTAPI_DB_NAME}/714_RoadDiff --differential`

**Comment by brianhatchl** [comment]
I believe this is because some conflation types were disabled in advanced options.  It is highly probably that the subset of matchers and mergers is ordered without any explicit intent when passed to the conflate command.

**Comment by bwitham** [comment]
@SeeBee2018 Did you explicitly de-activate any of the matchers in the adv opts when you ran that job? If so, disregard the missing matcher part. If not, that does need to be fixed.

About the ordering, though, yeah you're right. For some reason I was thinking Max had the ordering matching up with core in the work he did last year, but I guess not. Initially, I was thinking that the reason the ordering didn't use to matter that much and that now it does is due to the recent addition of the generic matchers, which get put at the very end. That doesn't really make sense though, b/c they're only supposed to kick in and match when no other matcher can conflate a feature, so it *should* be ok that they come before a specific matcher but apparently its not...will look into that. 

Regardless, the collection relation matcher I just merged in always needs to be at the end. I'll go ahead and try to check for that that in the core matcher autocorrect code that's in place, but it would be nice to see the matchers coming in the same order every time for debugging purposes anyway.

**Comment by bwitham** [comment]
To add to that, the Network config has its own matcher ordering which makes things even more confusing. I'm going to try to get rid of that in: https://github.com/ngageoint/hootenanny/issues/3722

**Comment by brianhatchl** [comment]
@bobi7 can get the order to match the default from ConfigOptions.asciidoc with some filtered out per advanced options.  Will also look at the order in NetworkAlgorithm.conf.  The only thing I see different other than swapping out Network for Highway is the order of Poi.js and River.js.


ConfigOptions (default)
```
hoot::BuildingMatchCreator
hoot::ScriptMatchCreator,Poi.js
hoot::HighwayMatchCreator
hoot::ScriptMatchCreator,River.js
hoot::PoiPolygonMatchCreator
hoot::ScriptMatchCreator,Area.js
hoot::ScriptMatchCreator,Railway.js
hoot::ScriptMatchCreator,PowerLine.js
hoot::ScriptMatchCreator,Point.js
hoot::ScriptMatchCreator,Line.js
hoot::ScriptMatchCreator,Polygon.js
hoot::ScriptMatchCreator,PointPolygon.js
```

NetworkAlgorithm.conf
```
hoot::BuildingMatchCreator
hoot::NetworkMatchCreator
hoot::PoiPolygonMatchCreator
hoot::ScriptMatchCreator,Area.js
hoot::ScriptMatchCreator,River.js
hoot::ScriptMatchCreator,Poi.js
hoot::ScriptMatchCreator,Railway.js
hoot::ScriptMatchCreator,PowerLine.js
hoot::ScriptMatchCreator,Point.js
hoot::ScriptMatchCreator,Line.js
hoot::ScriptMatchCreator,Polygon.js
hoot::ScriptMatchCreator,PointPolygon.js
```

**Comment by brianhatchl** [comment]
NVM, the services reads in NetworkAlgorithm.conf so we will use that to preserve order when Network is requested.

**Comment by bwitham** [comment]
That can be done for now. Soon I'm going to remove those matchers from NetworkAlgorithm.conf so two different lists don't have to be maintained. All you'll have to do after that is substitute out the highway matcher for Network.

**Comment by bobi7** [comment]
@bwitham thanks for pointing that last part out. i was wondering why i didnt see the network merger in the configOptions.ascii

**Comment by ghost** [comment]
> @SeeBee2018 Did you explicitly de-activate any of the matchers in the adv opts when you ran that job? If so, disregard the missing matcher part. If not, that does need to be fixed.
> 
> About the ordering, though, yeah you're right. For some reason I was thinking Max had the ordering matching up with core in the work he did last year, but I guess not. Initially, I was thinking that the reason the ordering didn't use to matter that much and that now it does is due to the recent addition of the generic matchers, which get put at the very end. That doesn't really make sense though, b/c they're only supposed to kick in and match when no other matcher can conflate a feature, so it _should_ be ok that they come before a specific matcher but apparently its not...will look into that.
> 
> Regardless, the collection relation matcher I just merged in always needs to be at the end. I'll go ahead and try to check for that that in the core matcher autocorrect code that's in place, but it would be nice to see the matchers coming in the same order every time for debugging purposes anyway.

@bwitham  yes,  anything that did not pertain to roads was disabled to speed up processing time.

**Comment by bwitham** [comment]
Ok, thanks.  So, we really just have the ordering problem. I have a temp fix that will be available in the next nightly that should let you run that job and get the correct. @bobi7 is working on a longer term solution, after which I'll remove the temp code.

**Comment by bobi7** [comment]
was running a little test and noticed something a bit interesting with my network conflation algorithm.

`hoot.bin conflate --info -C NetworkAlgorithm.conf -D writer.include.conflate.score.tags=false -D hootapi.db.writer.overwrite.map=true -D writer.text.status=true -D job.id=fa690867-41fb-4eaa-8f67-45b03934022d -D api.db.email=1@hootenanny -D match.creators=;hoot::ScriptMatchCreator,Area.js;hoot::BuildingMatchCreator;hoot::ScriptMatchCreator,CollectionRelation.js;hoot::ScriptMatchCreator,Line.js;hoot::ScriptMatchCreator,Point.js;hoot::ScriptMatchCreator,PointPolygon.js;hoot::ScriptMatchCreator,Polygon.js;hoot::ScriptMatchCreator,Poi.js;hoot::PoiPolygonMatchCreator;hoot::ScriptMatchCreator,PowerLine.js;hoot::ScriptMatchCreator,Railway.js;hoot::HighwayMatchCreator -D merger.creators=;hoot::ScriptMergerCreator;hoot::BuildingMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::PoiPolygonMergerCreator;hoot::ScriptMergerCreator;hoot::ScriptMergerCreator;hoot::HighwayMergerCreator hootapidb://${HOOTAPI_DB_USER}:${HOOTAPI_DB_PASSWORD}@${HOOTAPI_DB_HOST}:${HOOTAPI_DB_PORT}/${HOOTAPI_DB_NAME}/1 hootapidb://${HOOTAPI_DB_USER}:${HOOTAPI_DB_PASSWORD}@${HOOTAPI_DB_HOST}:${HOOTAPI_DB_PORT}/${HOOTAPI_DB_NAME}/2 hootapidb://${HOOTAPI_DB_USER}:${HOOTAPI_DB_PASSWORD}@${HOOTAPI_DB_HOST}:${HOOTAPI_DB_PORT}/${HOOTAPI_DB_NAME}/Merged_ToyTest`

Curious what happens here since the conf is the Network one but that last option is `hoot::HighwayMatchCreator` which should be `NetworkMatchCreator`.

I added the swap to my PR but was just wondering if it overwrites the options with whats in the conf or has this been wrong the entire time?

**Comment by bwitham** [comment]
yikes. The two should conflict with each other and end up causing a bunch of reviews b/c of shared matches between them....but we haven't been seeing that so maybe not.

**Comment by brianhatchl** [comment]
closed by https://github.com/ngageoint/hootenanny/issues/3958
