### ISSUE TITLE
Missing export/add additional layer option after resolving reviews

### ISSUE THREAD

**Issue by mjeffe98** [ngageoint/hootenanny-ui#180]
When you resolve all reviews either manually by stepping through and resolving or using the Complete Review | Resolve all remaining option, the export/add new layer to conflate buttons are missing.  This is missing in both the release and develop branches.  @jchoi1267 @sisskind was this intentionally removed or is a form not loading after resolving reviews?

![hoot_export_results](https://cloud.githubusercontent.com/assets/7560096/12525806/2cb06c06-c11c-11e5-864f-4f947fc54a9f.png)

**Comment by jchoi1267** [comment]
This was caused by .review element was being removed while being in use. It was handled by conflict.deactivate function which is used widely and some needed to remove .review and others handled it by itself. Had to go through each function to make sure whether it was not being used when deactivated if in use add switch to prevent it from being removed

**Comment by mjeffe98** [comment]
I don't see this functioning in latest on develop (0.2.20-259-gc43c1da-dirty)
