### ISSUE TITLE
Update Cookie Cutter Boundary Tolerance

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#192]
2km buffer is not practical for smaller conflation areas and may prove more valuable to enable users to choose the proper thresholds to perform the cookie cutter capability for isolated conflation.  Provide the ability to allow user defined buffer capability for cookie cutter conflation.

**Comment by sisskind** [comment]
@mjeffe Ready for test.  Should be able to see 'Cookie Cutter Alpha Shape Buffer' under Cookie Cutter & Horizontal Options when Cookie Cutter & Horizontal is the selected conflation type.

![issue-192](https://cloud.githubusercontent.com/assets/6191659/13537994/f899a61a-e215-11e5-98a2-d7debb60a17e.png)

**Comment by mjeffe98** [comment]
@sisskind I assume that the units are km, correct?  We might want to have something that is configurable since it's just a blank number field.  Also the default value is 0.  Does that mean if the user does not do anything in this option that no buffer will be used?  I would assume that the 2km buffer would be the default.  Also is the value entered representing both the internal and external buffer i.e. a buffer value of 1 represents (assuming this is km) a 1 km buffer inside the alpha shape and 1 km buffer outside?

**Comment by sisskind** [comment]
@mjeffe98 I don't want to go too crazy with it since it should follow same paradigm as all advanced options.  Burden should be on user to understand the values.

Yes -- if user leaves value as 0, nothing happens.  Think there was confusion over 2km buffer previously, unless I am using wrong variable.

**Comment by mjeffe98** [comment]
does look like the parameter is getting passed properly.  It's a bit difficult to completely assess the final product but we can look at that later down the road.
