### ISSUE TITLE
Add cucumber tests for dataset export

### ISSUE THREAD

**Issue by bwitham** [ngageoint/hootenanny-ui#299]
Do this after ngageoint/hootenanny#385 is done. 

* create test-files/ui/fgdb-export.feature
* create test-files/ui/osm-export.feature
* create test-files/ui/shapefile-export.feature

**Comment by brianhatchl** [comment]
https://github.com/ngageoint/hootenanny/pull/751

FGDB is not implemented at this point because the capybara technique I'm using to upload a file is only working with a single file.  I've added a ticket to add support for zipped osm and gdb datasets to hoot, https://github.com/ngageoint/hootenanny-ui/issues/449.
