### ISSUE TITLE
Error loading review layer if input layer(s) has been deleted

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#377]
When one or both input layer(s) for a review layer have been deleted, the review layer fails to load/render.

**Comment by mjeffe98** [comment]
This is the error message when you load a review layer where one of the input layers has been deleted.  This leaves the UI in a broken state requiring reloading.  I personally think we shouldn't close https://github.com/ngageoint/hootenanny-ui/issues/356 until this is done because if the user does delete an input layer and not the merged layer, the bookmark will remain and the issue will persist.  

Could not determine input layer 2. It will not be loaded.

**Comment by sisskind** [comment]
@mjeffe98 ready for test.  To test, run conflation job, then remove one/both of input layers.  Should be able to re-load review layer and run through review process.

**Comment by mjeffe98** [comment]
@sisskind I'm still seeing the application hang after I delete one/both input layers associated with a merge layer that has unresolved reviews.  Just spins while it checks for reviewable features.  Also get an error that it couldn't load the input layers, which makes sense since it was deleted.

Hootenanny Core - Version: 0.2.24_328_g976ccd5_dirty - Built By: vagrant

**Comment by brianhatchl** [comment]
My b.  I forgot to update the hoot-ui submodule commit.  Stand by.

**Comment by brianhatchl** [comment]
Do a pull and `git submodule update` now.

**Comment by mjeffe98** [comment]
yes sir :)
