### ISSUE TITLE
GoTo Review failing for ways

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#431]
Error: 
```
Failed to execute 'getPointAtLength' on 'SVGPathElement': The provided float value is non-finite
```

Inspect why variables beforeLength and afterLength are not being populated and resolve so that the goto review function will work for lines and polygons.

**Comment by sisskind** [comment]
@mjeffe98 ready for test.  should be able to go to review for ways, not just nodes.

**Comment by mjeffe98** [comment]
@sisskind is this applicable only for the review bookmark where you click on the magnifier to goto a specific review?  If so that it's working on reviews for ways.

**Comment by mjeffe98** [comment]
@sisskind after our conversation this morning you stated that this was a function called when you click on the "show review relations" icon for ways but other than clicking on the circle with the letter e.g. A, B, C, etc.. I can't think of anything else executes a "GoTo Review" action.  In the simple use case where you have a review involving a single way against another way (in DcGisRoads vs. DcTigerRoads for ex), you can click on the show review relations and have it display a letter representing the review and then click on the letter but this just re-centers the map to the same review.  Not much value add for that use-case since you already have the review in the active map.

For use cases where the road review involves a relation,  https://github.com/ngageoint/hootenanny-ui/issues/383 is still an issue.  Given the complex nature of these road reviews, not sure how you could even use the show review relations option (see screen shot for typical example in PaP where you have a single red road segments reviewed against a relation of several blue road segments).

![image](https://cloud.githubusercontent.com/assets/7560096/15403603/ac41905a-1dae-11e6-8279-951fb1d7c783.png)

**Comment by sisskind** [comment]
Was just for the letter bubbles and not #383 -- will close.
