### ISSUE TITLE
Refactor service and UI code to handle variable numbers of relation members

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#450]
See ngageoint/hootenanny#221 for more details.

Currently all the review code revolves around assumption that there are only 2 member in a review relation. With new core implementation this will need to be changed to handle variable numbers of members.

**Comment by sisskind** [comment]
@mjeffe98 ready for test

**Comment by mjeffe98** [comment]
@sisskind what specifically I am looking for?  Should this be testing against a particular set of data that has many to many building matches?

**Comment by sisskind** [comment]
@treycaldwell can help you through it as well, but check the commit for issue 136, which lists the test data included.  You should be able to load the data, conflate, and see the data table cycle through the review.

**Comment by mjeffe98** [comment]
the test data I used was in test-files\cases\unifying\building-4 since there were many to many reviews.  I suppose the intent here is not to break up the buildings in Input1 and Input2 into separate reviews (e.g. Target South vs Target Grocery, Target - Aurora South vs. Target, etc.) but allow a single review for the collection of buildings in red/blue and proceed with a many:many conflate.

![image](https://cloud.githubusercontent.com/assets/7560096/16058099/a28c2e16-3231-11e6-9bf0-4d589e84c0c7.png)

**Comment by mjeffe98** [comment]
Nevermind.  I compared it to the old way (prior to the commit) and it looks like when you conflate the same buildings, no review is generated so you don't get to see the constituent parts for each building relation.  Now you are able to.
