### ISSUE TITLE
Incorrectly Rendering Map Layers

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#452]
When you click the "related reviews" button on the pallette on a feature that is part of a RELATION review and no related reviews display, and then pan and zoom around, the map layer remains at the location and zoom level it was at when you clicked "related reviews".

**Comment by sisskind** [comment]
https://github.com/DigitalGlobe/VGI-team-repo/issues/136

**Comment by mjeffe98** [comment]
Now when you are able to click on a feature in a review b/w a relation and a way, it seems to display the bubble letters and allow users to pan, zoom, etc.  I have also observed the same behavior that @brianhatchl reported in https://github.com/ngageoint/hootenanny-ui/pull/460#issuecomment-221953594 where you cannot view related reviews on a feature that is part of a relation because the  relation is either not clickable to open the radial menu or it doesn't display the show related reviews icon.  When you click on the feature that is not a relation, this does have the radial menu with the show related review options and displays A-Z letters with lines pointing to each segment.
