### ISSUE TITLE
Add MGCP to the list of on-the-fly translations

### ISSUE THREAD

**Issue by mattjdnv** [ngageoint/hootenanny-ui#487]
See Hootenanny #793 for the MGCP to/from english scripts

* Add MGCP to the list on-the-fly translations
* Add MGCP pre-sets for feature creation

**Comment by brianhatchl** [comment]
MGCP is now an option in the schema switcher, along with TDS and OSM.

**Comment by mjeffe98** [comment]
I see MGCP added for the schema switcher but I am not getting any presets when I select that option. There are instances when a preset or list of presets might appear but these seem to be associated with non-mgcp options (osm, tds)  since I can't click on them to select.  From this perspective it only appears that 50% of this ticket is functioning.  Am I missing something?

![image](https://cloud.githubusercontent.com/assets/7560096/16025919/67150ab8-317f-11e6-87f5-b44b9a28201d.png)

**Comment by brianhatchl** [comment]
No, I added a cucumber test that validated the schema of an existing feature updated when changed to MGCP, but not a new feature expecting a list of presets.  Probably a bug or piece missing.
