### ISSUE TITLE
Replace progress bar on bulk import

### ISSUE THREAD

**Issue by sisskind** [ngageoint/hootenanny-ui#598]
Repeat https://github.com/ngageoint/hootenanny-ui/issues/545 for bulk import.

**Comment by rmrice** [comment]
So I replaced the progress bar with the loading/spinner icon for bulk import. Before I make a PR, just wanted to note that I referenced the icon the "old way" (`.classed('_icon _loading')`) because the spinner wasn't on the SVG icon list. I can call it as an svg like what was done in #611 but I want to make sure I don't mess up the svg list / sprite sheet if I add it in :grin: .

**Comment by sisskind** [comment]
@rmrice you are in good shape. We will eventually replace icons with svgs, but for now can continue with existing paradigm.
